/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SalarioApiRouteImport } from './routes/salario-api'
import { Route as SalarioRouteImport } from './routes/salario'
import { Route as RecomendacoesRouteImport } from './routes/recomendacoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SalarioApiRoute = SalarioApiRouteImport.update({
  id: '/salario-api',
  path: '/salario-api',
  getParentRoute: () => rootRouteImport,
} as any)
const SalarioRoute = SalarioRouteImport.update({
  id: '/salario',
  path: '/salario',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendacoesRoute = RecomendacoesRouteImport.update({
  id: '/recomendacoes',
  path: '/recomendacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/salario': typeof SalarioRoute
  '/salario-api': typeof SalarioApiRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/salario': typeof SalarioRoute
  '/salario-api': typeof SalarioApiRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/salario': typeof SalarioRoute
  '/salario-api': typeof SalarioApiRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/recomendacoes'
    | '/salario'
    | '/salario-api'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/recomendacoes'
    | '/salario'
    | '/salario-api'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/recomendacoes'
    | '/salario'
    | '/salario-api'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  RecomendacoesRoute: typeof RecomendacoesRoute
  SalarioRoute: typeof SalarioRoute
  SalarioApiRoute: typeof SalarioApiRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salario-api': {
      id: '/salario-api'
      path: '/salario-api'
      fullPath: '/salario-api'
      preLoaderRoute: typeof SalarioApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salario': {
      id: '/salario'
      path: '/salario'
      fullPath: '/salario'
      preLoaderRoute: typeof SalarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendacoes': {
      id: '/recomendacoes'
      path: '/recomendacoes'
      fullPath: '/recomendacoes'
      preLoaderRoute: typeof RecomendacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  RecomendacoesRoute: RecomendacoesRoute,
  SalarioRoute: SalarioRoute,
  SalarioApiRoute: SalarioApiRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
